sudo: true
dist: trusty
language: cpp
# run on new infrastructure
cache: apt
deploy:
  provider: releases
  api_key: $ACCESS_TOKEN
  file:
  - "riscv-tools.tar.bz2"
  skip_cleanup: true
  on:
    tags: true
before_script:
- if [ -d Bluespec-2015.09.beta2 ] ; then echo bluespec cached; else curl http://www.bluespec.com/downloads/Bluespec-2015.09.beta2.tar.gz | tar -zxf - ; fi
- mkdir -p lib
- ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 lib/libgmp.so.3
env:
  global:
    - RISCV="/home/travis/riscv_install"
    - BLUESPECDIR=$PWD/Bluespec-2015.09.beta2/lib
    - PATH=$PATH:$PWD/Bluespec-2015.09.beta2/bin
    - LD_LIBRARY_PATH=$PWD/lib
  matrix:
    - CONNECTAL_TEST=examples/echo CONNECTAL_ARCH=verilator
# required packages to install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bison
      - build-essential
      - flex
      - g++-4.8
      - gawk
      - gcc-4.8
      - gperf
      - libgmp-dev
      - libjsoncpp-dev
      - libmpc-dev
      - libmpfr-dev
      - linux-headers-generic
      - python-dev
      - python-ply
      - texinfo
      - verilator

before_install:
  # make install destination
  - mkdir -p $RISCV
  # use gcc 4.8
  - export CXX=g++-4.8 CC=gcc-4.8
  - sed -i s/JOBS=16/JOBS=2/ riscv-tools/build.common

# extra time duing long builds
install: travis_wait

script:
- ./build-toolchain.sh
- tar -jcf riscv-tools.tar.bz2 riscv
