language: cpp
# run on new infrastructure
sudo: false
cache: apt
before_script:
- docker pull jameyhicks/riscv-tools
env:
  matrix:
    - CONNECTAL_TEST=examples/echo CONNECTAL_ARCH=verilator
# extra time duing long builds
install: travis_wait

script:
- cd connectal/$CONNECTAL_TEST; docker run -it -u travis -v $PWD/$PWD -w $PWD jameyhicks/riscv-tools make build.$CONNECTAL_ARCH
