language: cpp
# run on new infrastructure
sudo: false
cache: apt
# required packages to install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - verilator

env:
  global:
    - RISCV="/home/travis/riscv_install"

before_install:
  # make install destination
  - mkdir -p $RISCV
  - sed -i s/JOBS=16/JOBS=2/ riscv-tools/build.common

# extra time duing long builds
install: travis_wait

script: ./build-verilator.sh
