# TODO: FIXME: XXX: Get rid of these defines:
RISCV_HOME=$(HOME)/riscy-processors/
RISCV_BUILD?=$(RISCV_HOME)/build
RISCV_TOOLS?=$(RISCV_HOME)/riscv
RISCV?=$(RISCV_TOOLS)

PROC=RV64G_redux

# suppress "duplicate folder" and "unfolding over ... steps" warnings
# CONNECTALFLAGS += --bscflags=" -suppress-warnings S0073:G0024 "

include $(RISCV_HOME)/procs/Makefile.procs
