PROC=RV64G_multicycle

# suppress "duplicate folder" and "unfolding over ... steps" warnings
# CONNECTALFLAGS += --bscflags=" -suppress-warnings S0073:G0024 "

include $(RISCV_HOME)/procs/Makefile.procs
